---

- hosts:
  - scratch
  become: yes
  vars:
    ubuntu_password: changeme_iP4Opoozaj
    swap_file_path: /swap.img
    swap_size: 2000 # swap is not necessary, but useful in case of using cheaper low-memory instances.
    chrome_deb_url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    # Note: this NoMachine deb URL may change (it happened once) and it's not directly available
    # on their website. If you get errors from APT about corrupted package, this means
    # that there is a new URL. Try downloading installation package from website,
    # then go to browser devtools and extract direct link.
    nomachine_deb_url: https://download.nomachine.com/download/7.0/Linux/nomachine_7.0.211_4_amd64.deb
  tasks:
  - name: Add APT repository for x2go
    apt_repository:
      repo: ppa:x2go/stable
      state: present

  - name: Upgrade everything
    apt:
      upgrade: dist
      update_cache: yes

  - name: Install packages
    apt:
      pkg:
      - x2goserver
      - x2goserver-xsession
      - xfce4
      - firefox
      - evince 
      - eog
      - libappindicator3-1
      - fonts-liberation 
      - gedit
      - xfce4-screenshooter
      - kolourpaint
      - unzip

  - name: Remove screensaver (saves bandwidth)
    apt:
      name: xscreensaver
      state: absent

  - name: Nuke old config
    file:
      path: /home/ubuntu/.config
      state: absent

  - name: Put customized config (Xfce panel setup, Chrome profile with smooth scrolling disabled)
    shell: "cp -r homedir/{{ item }} /home/ubuntu && chown -R ubuntu:ubuntu /home/ubuntu/{{ item }}"
    with_items:
    - ".config"
    - ".local"

  - name: Set interactive login password
    user:
      name: ubuntu
      password: "{{ ubuntu_password | password_hash('sha512') }}"

  - name: Enable password authentication
    lineinfile: 
     dest: /etc/ssh/sshd_config
     regexp: '^#?PasswordAuthentication'
     line: 'PasswordAuthentication yes'

  - name: Restart SSH server for enabling password authentication
    service:
      name: ssh
      state: restarted
 
  - name: Make ubuntu user root-like
    lineinfile:
      dest: /etc/sudoers
      line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Install Google Chrome
    apt:
      deb: "{{ chrome_deb_url }}"

  - name: Install NoMachine
    apt:
      deb: "{{ nomachine_deb_url }}"

  - name: Configure NoMachine for XFCE
    lineinfile:
     dest: /usr/NX/etc/node.cfg
     regexp: '^DefaultDesktopCommand'
     line: 'DefaultDesktopCommand "/usr/bin/X11/startxfce4"'

  - name: Check if swap file exists
    stat:
      path: "{{ swap_file_path }}"
    register: swap_result

  - name: Create and enable swap file
    command: '{{ item }}'
    with_items:
    - 'dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ swap_size }}'
    - 'chmod 600 {{ swap_file_path }}'
    - 'mkswap {{ swap_file_path }}'
    - 'swapon {{ swap_file_path }}'
    when: not swap_result.stat.exists

